#!/bin/bash

#Script:                   Ops 301 Ops Chall Class 05
#Author:                   Bruce Martin
#Date of Latest Revision:  09/06/200

#Declaration of Purpose:  Clearing Log Files


#Declaration of Variables

#Declaration of Functions


#Main

cd /var/log
echo "Contents Before"
cat syslog
cd /var/log
cat dev/null > syslog
echo "Contents Afterwards"
cat syslog

cd /var/log
echo "Contents Before"
cat wtmp
cd /var/log
cat dev/null > wtmp
echo "Contents Afterwards"
cat wtmp


#End

