#!/bin/bash

# Script:                       Ops 301 Ops Chall Class-05
# Author:                       
# Date of latest revision:      
# Purpose:                      Demo

# How to view a file's contents

cat testfile.txt

# How to clear a file's contents

cat /dev/null > testfile.txt
